# This is a config for E2B sandbox template.
# You can use template ID (oerix5sdiqjkw41flspo) or template name (vibegourab) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibegourab") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibegourab") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibegourab')

team_id = "fd79eae7-454b-4e06-b04d-d2459ba1d72b"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibegourab"
template_id = "oerix5sdiqjkw41flspo"
